# Funciones aleatorias

Hablando de funciones no podemos olvidar las funciones aleatorias encontradas en el módulo `random`. [En la documentación oficial](https://numpy.org/doc/stable/reference/random/index.html) encontraréis el listado completo con ejemplos de uso.

Tenemos funciones para generar arrays con `datos aleatorios` y `permutaciones`. También hay muchas enfocadas a generar muestras de distribuciones de probabilidad pensadas para visualizar estadística.

Vamos a practicar algunas de las dos primeras.

## Datos aleatorios

In [1]:
import numpy as np

In [2]:
# número decimal entre 0 y 1
np.random.rand()

0.7680101619277756

In [3]:
# array 1D de decimales entre 0 y 1
np.random.rand(4)

array([0.72084712, 0.80825326, 0.82474567, 0.97230455])

In [4]:
# array 2D de decimales entre 0 y 1
np.random.rand(4,2)

array([[0.81744578, 0.15197055],
       [0.50372367, 0.6965973 ],
       [0.11293527, 0.43135388],
       [0.02770614, 0.41214557]])

In [5]:
# array 3D de decimales entre 0 y N
np.random.uniform(10, size=[2,2,2])

array([[[3.74760238, 7.62401971],
        [3.63392123, 8.61055791]],

       [[2.6745891 , 6.38481823],
        [9.40600646, 6.88960354]]])

In [6]:
# array 4D de decimales entre -N y M
np.random.uniform(-10, 10, size=[2,2,2,2])

array([[[[-7.50538702, -0.80481866],
         [-7.67411433,  5.50597444]],

        [[-5.63265944, -3.01338459],
         [-2.50118336,  7.0095723 ]]],


       [[[-1.43931522, -9.81098583],
         [ 4.91410386,  4.89063587]],

        [[-0.61658133, -3.0283638 ],
         [-6.95997807, -2.72690653]]]])

In [7]:
# número entero entre 0 y N
np.random.randint(10)

9

In [8]:
# array de enteros entre 0 y N
np.random.randint(10, size=[3,2])

array([[2, 7],
       [2, 9],
       [9, 2]])

In [9]:
# array de enteros entre -N y M
np.random.randint(-10, 10, size=[3,2])

array([[ 9, -1],
       [-2,  9],
       [ 6,  0]])

In [10]:
# array uniforme con curva gaussiana
np.random.normal(size=20)

array([ 0.37339188,  1.45643039,  1.06202495, -1.08470048,  0.78925181,
        1.5216387 ,  0.50645487,  1.50459631, -0.02915903,  1.76087365,
        0.32035265,  0.00646156, -2.0026798 , -0.53642851, -0.22037108,
       -0.24315516,  1.41508814,  0.43611953, -2.75806806,  1.61517135])

## Permutaciones

In [11]:
arr = np.arange(10)

arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
# desordenar un array
np.random.shuffle(arr)

arr

array([9, 3, 1, 4, 7, 0, 2, 5, 8, 6])

In [13]:
# generar secuencia permutada a partir de un número
np.random.permutation(15)

array([12,  4, 13,  7,  1,  8,  0,  9,  5, 14,  2, 11, 10,  6,  3])