# Filtrado de arrays

En esta lección vamos a repasar algunas funciones para filtrar arrays. Para más información sobre las funciones disponibles no olvidéis pasaros por [la documentación oficial](https://numpy.org/doc/stable/reference/index.html).

## Filtro unique

Devuelve un array de una dimensión borrando todos los elementos duplicados:

In [15]:
import numpy as np

In [16]:
# generamos un array con números aleatorios repetidos
arr = np.random.randint(0, 10, 40)

In [17]:
arr

array([0, 1, 7, 0, 7, 3, 0, 1, 8, 1, 3, 2, 0, 0, 7, 4, 4, 8, 6, 6, 6, 4,
       7, 5, 7, 3, 8, 0, 9, 1, 9, 3, 5, 7, 0, 6, 4, 5, 4, 5])

In [18]:
# aplicamos el filtro unique
np.unique(arr)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Filtro in1d

Devuelve un array de una dimensión indicando si los elementos de una lista se encuentran en otro array:

In [19]:
np.in1d([-1, 4, 8, 12], arr)

array([False,  True,  True, False])

## Filtro where

Sirve para generar un array filtrado a partir de una condición y un valor por defecto:

In [20]:
# generamos un array con números aleatorios
arr_1 = np.random.uniform(-5, 5, size=[3,2])

arr_1

array([[ 0.4684631 ,  4.1755961 ],
       [-4.73431978, -3.89002402],
       [-3.68383417,  3.32266983]])

In [21]:
# creamos un filtro que establece los negativos a 0
arr_2 = np.where(arr_1<0, 0, arr_1)

arr_2

array([[0.4684631 , 4.1755961 ],
       [0.        , 0.        ],
       [0.        , 3.32266983]])

In [22]:
# añadimos otro filtro que establece los positivos a 1
arr_2 = np.where(arr_2>0, True, arr_2)

arr_2

array([[1., 1.],
       [0., 0.],
       [0., 1.]])

## Filtros booleanos

Permiten hacer comprobaciones lógicas en los arrays de booleanos:

In [23]:
# definimos un array de booleanos
arr_bool = np.array([True,True,True,False])

In [24]:
# comprobar si todos los elementos del array son True
arr_bool.all()

False

In [25]:
# comprobar si al menos un elementos del array es True
arr_bool.any()

True

También funciona con múltiples dimensiones pasando el eje:

In [26]:
# definimos un array de booleanos 2d
arr_bool_2d = np.array(
    [
        [False, True],
        [False, True],
        [False, True]
    ]
)

arr_bool_2d

array([[False,  True],
       [False,  True],
       [False,  True]])

In [27]:
# comprobar si alguna de las columnas es todo True
arr_bool_2d.all(0)

array([False,  True])

In [28]:
# comprobar si alguna de las filas tiene algún True
arr_bool_2d.any(1)

array([ True,  True,  True])